# <center> Тема 2. NUMPY

1. [Ключевые нюансы numpy](#Ключевые-нюансы-numpy)
2. [Линейная алгебра](#Линейная-алгебра)
3. [Прикладная статистика](#Прикладная-статистика)
4. [kNN - метод ближайших соседей](#kNN---метод-ближайших-соседей)

# Ключевые нюансы numpy

Рекомендуется ознакомится с решением 100 задачек в numpy:
https://pythonworld.ru/numpy/100-exercises.html

In [1]:
import numpy as np
# Скорость 
my_arr = np.arange(1000000)
my_list = list(range(1000000))
# %timeit for _ in range(10): my_arr2 = my_arr * 2 
# %timeit for _ in range(10): my_list2 = list(map(lambda x: x * 2, my_list))

In [19]:
# Индексация
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[0, 1])
print(a[:2, :3])
print(a[1:2, 2:3])
print(a[1:, 2:])
print(a[1, :])    
print(a[1:2, :])  
print(a[[1], :]) 
print(a[:, 1])
print(a[:, 1:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[1 2 3]
 [5 6 7]]
[[7]]
[[ 7  8]
 [11 12]]
[5 6 7 8]
[[5 6 7 8]]
[[5 6 7 8]]
[ 2  6 10]
[[ 2]
 [ 6]
 [10]]


In [9]:
np.zeros_like([[2,3], [1,5]]).

array([[0, 0],
       [0, 0]])

In [44]:
# Создание различных шаблонных массивов

# Нулевой массив 
print(np.zeros(5))
print(np.zeros((2, 4)))
print(np.zeros_like([[2,3], [1,5]]))
print(np.empty((2, 4)))
# Единичный массив
print(np.ones(5))
print(np.ones((2, 4)))
print(np.ones_like([[2,3], [1,5]]))

# Одномерный массив целочисленных положительных чисел
print(np.arange(15))

# Единичный массив / матрица
print(np.eye(2))
print(np.identity(2))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0]
 [0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [33]:
# Размерность массивов
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b.shape)

# Изменение размерности (умноженные размерности совпадают)
v = np.array([1,2,3]) 
print(v, "\n", v.reshape(3, 1))

print(np.arange(16).reshape(2, 4, 2))
print(np.arange(16).reshape(1, 4, 2, 2))

# Изменение размерности (новая размерность другая - заполнение нулями)
a0 = np.arange(4)
a0.resize((8,))
print(a0)

(3, 3)
[1 2 3] 
 [[1]
 [2]
 [3]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[0 1 2 3 0 0 0 0]


Numpy позволяет оперировать массивами разных размерностей.
Например:

In [43]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [66]:
np.array([1,0,1]*4).reshape(3,2,2)

array([[[1, 0],
        [1, 1]],

       [[0, 1],
        [1, 0]],

       [[1, 1],
        [0, 1]]])

In [36]:
vv = np.tile(v, (4, 1))  # Стакаем сверху вниз 4 копии v
print(vv) 
y = x + vv  # Складываем два массива
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Иллюстрация броадкастинга

In [29]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x.shape)
v = np.array([1, 0, 1])
print(v.shape)
v4 = np.array([1, 0, 1, 4])
y = x + v 
print(y)

(4, 3)
(3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**Вывод:** не обязательно приводить массивы к одной размерности для осуществления математических операций. Памятка по броадкастингу:
1. Если массивы не имеют одинакового ранга, размерность массива нижнего ранга изменяется с первого до тех пор, пока обе размерности не будут иметь одинаковую длину.
2. Считается, что оба массива совместимы в одном измерении, если они имеют одинаковый размер в этом измерении, или если один из массивов имеет размер 1 в этом измерении.
3. Массивы могут броадкаститься вместе, если они совместимы во всех измерениях.
4. После броадкастинга каждый массив ведет себя так, как если бы он имел размерность, равную элементарному максимуму размерности двух входных массивов.
5. В любом измерении, где один массив имеет размер 1, а другой больше 1, первый массив ведет себя так, как если бы он был скопирован по этому измерению.

Документация:

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [42]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [44]:
np.arange(9).reshape(3, 3) * np.arange(3).reshape(3, 1)

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16]])

In [45]:
np.arange(9).reshape(3, 3) * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
np.array([[[1,2,3],[3,4,5], [6,7,8]]])

(1, 3, 3)

In [75]:
c

array([[4, 3, 5],
       [1, 2, 1]])

In [40]:
np.sort(np.sort(c, axis=0)).reshape(-1)

array([1, 1, 2, 3, 4, 5])

In [39]:
np.sort(c.reshape(-1))

array([1, 1, 2, 3, 4, 5])

In [44]:
# Сортировка

c = np.array([[4, 3, 5], [1, 2, 1]])
print(np.sort(c, axis=1))

# Возвращает индексы элементов, которые были отсортированы 
j = np.argsort(c)
print(j)
print(c[:, j])


np.array([[[1,2,3],[3,4,5], [6,7,8]]]).argpartition(kth = 2, axis = 1)

[[3 4 5]
 [1 1 2]]
[[1 0 2]
 [0 2 1]]
[[[3 4 5]
  [4 5 3]]

 [[2 1 1]
  [1 1 2]]]


array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]])

In [501]:
np.array([[1,3,5],[5,4,5],[1,2,10],[5,4,6]]).argpartition(kth = 2, axis = 1)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [61]:
np.array([[10,3,5, 3],[5,4,5, 5],[1,2,10, 7],[5,4,6, 15]]).argsort(axis=1)

array([[1, 3, 2, 0],
       [1, 0, 2, 3],
       [0, 1, 3, 2],
       [1, 0, 2, 3]])

In [505]:
np.array([np.arange(5)]) * np.ones((5,5)).argpartition(kth = 3, axis=1)

array([[ 0,  2,  0,  3, 16],
       [ 0,  2,  0,  3, 16],
       [ 0,  2,  0,  3, 16],
       [ 0,  2,  0,  3, 16],
       [ 0,  2,  0,  3, 16]])

In [1]:
# Условия и циклы
for i in np.array([[1,2,3],[4,5,6]]):
    print(i)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print(data[names == "Bob"])
print(data[names == 'Bob', 2:])

[1 2 3]
[4 5 6]
[[ 2.29999476 -1.75062293 -1.0300785   1.39901065]
 [-0.74521315  1.27618822  2.114178   -0.84018816]
 [ 0.0837459  -0.66660738 -0.74014551 -1.06166026]
 [-0.51779696 -0.24234596 -2.14649435 -0.51566222]
 [-0.29675832 -0.99429669  0.64156382 -0.30589642]
 [ 0.21377213 -0.56907918 -1.5049256  -0.5299902 ]
 [ 2.29322943  1.06701615 -1.09939326  0.67503473]]
[[ 2.29999476 -1.75062293 -1.0300785   1.39901065]
 [-0.51779696 -0.24234596 -2.14649435 -0.51566222]]
[[-1.0300785   1.39901065]
 [-2.14649435 -0.51566222]]


In [2]:
data

array([[ 2.29999476, -1.75062293, -1.0300785 ,  1.39901065],
       [-0.74521315,  1.27618822,  2.114178  , -0.84018816],
       [ 0.0837459 , -0.66660738, -0.74014551, -1.06166026],
       [-0.51779696, -0.24234596, -2.14649435, -0.51566222],
       [-0.29675832, -0.99429669,  0.64156382, -0.30589642],
       [ 0.21377213, -0.56907918, -1.5049256 , -0.5299902 ],
       [ 2.29322943,  1.06701615, -1.09939326,  0.67503473]])

In [4]:
# Присвоение по условию (если, то)
np.where(data, data>0, 0)

array([[0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 1],
       [0, 0, 1, 0]])

In [6]:
a = np.arange(10)
a
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [69]:
# Слияние массивов
x,y,z = np.arange(1,3), np.arange(3,5), np.arange(5,7)
print(np.concatenate([x,y,z]))

array2D_1 = np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
array2D_2 = np.array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Вертикальное слияние
print(f"Вертикальное : \n {np.vstack((array2D_1, array2D_2))}")

# Горизонтальное слияние
print(f"Горизонтальное : \n {np.hstack((array2D_1, array2D_2))}")

[1 2 3 4 5 6]
Вертикальное : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Горизонтальное : 
 [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [8]:
data

array([[ 2.29999476, -1.75062293, -1.0300785 ,  1.39901065],
       [-0.74521315,  1.27618822,  2.114178  , -0.84018816],
       [ 0.0837459 , -0.66660738, -0.74014551, -1.06166026],
       [-0.51779696, -0.24234596, -2.14649435, -0.51566222],
       [-0.29675832, -0.99429669,  0.64156382, -0.30589642],
       [ 0.21377213, -0.56907918, -1.5049256 , -0.5299902 ],
       [ 2.29322943,  1.06701615, -1.09939326,  0.67503473]])

In [9]:
np.apply_along_axis(lambda x: (x - max(x))**2, 0, data)

array([[0.00000000e+00, 9.16158577e+00, 9.88634894e+00, 0.00000000e+00],
       [9.27329120e+00, 0.00000000e+00, 0.00000000e+00, 5.01401131e+00],
       [4.91175900e+00, 3.77445478e+00, 8.14716274e+00, 6.05490134e+00],
       [7.93995018e+00, 2.30594608e+00, 1.81533289e+01, 3.66597221e+00],
       [6.74312656e+00, 5.15510174e+00, 2.16859253e+00, 2.90670812e+00],
       [4.35232486e+00, 3.40501178e+00, 1.30979109e+01, 3.72104430e+00],
       [4.57696811e-05, 4.37529585e-02, 1.03270403e+01, 5.24141139e-01]])

In [10]:
# Применение функции к разным осям массива
m = np.random.randn(3,2)
# Сначала указываем функцию, потом по какой оси, а затем указываем сам массив
print(np.apply_along_axis(lambda x: sum(x ** 2), 1, m)) 
print(np.apply_along_axis(lambda x: sum(x ** 2), 0, m)) 
# Обратим внимание, что у функции может быть только один аргумент - это значения массива из конкретной оси





[0.19565497 1.31895696 1.43533145]
[2.21932628 0.7306171 ]


In [19]:
np.round(0.3, 17) == np.round(3 * 0.1, 17)

False

In [18]:
np.allclose(0.3, 3*0.1)

True

In [21]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))

# Линейная алгебра

#### np

**diag** - вернуть диагональные (или недиагональные) элементы квадратной матрицы в виде 1D-массива, или преобразовать 1D-массив в квадратную матрицу с нулями на остальных элементах.

**dot, @** - матричное умножение

**trace** - вычислить сумму диагональных элементов (след матрицы)

#### linalg

**det**  определитель матрицы.

**eig** - вычислить собственные значения и собственные векторы квадратной матрицы.  

**inv** - вычислить обратную  матрицу любой квадратной матрицы (определитель должен быть не равен нулю)

**svd** - вычислить сингулярное разложение значений (SVD).

**solve** решение линейной системы уравнений Ax = b для x, где A - квадратная матрица. 

**lstsq** - вычислить оценки методом наименьших квадратов для Ax = b

In [26]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
w, v = np.linalg.eig(x)

In [37]:
x @ v[:, 0] == w[0]*v[:, 0]

array([False, False, False])

In [36]:
np.allclose(x @ v[:, 0], w[0]*v[:, 0])

True

In [133]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print(x.dot(np.ones(3)), np.dot(x, np.ones(3)), x @ np.ones(3))

[ 6. 15.] [ 6. 15.] [ 6. 15.]


In [95]:
from numpy.linalg import inv, det
mat = np.random.randn(5, 5)
print(inv(mat))
print(det(mat))

[[-0.07804272  0.98875349 -0.18804848  0.41857286  0.02069609]
 [ 0.32048679 -2.91090309  1.25514445  1.15589183 -0.35306481]
 [ 0.0262801   1.4123499  -0.32113901 -1.21282462  1.07864606]
 [-0.01365896 -1.96130517  0.31569287 -0.02262023  0.24753756]
 [-0.29258148 -2.15714787  0.68313371  0.2973067  -0.12866259]]
2.1600950027772745


## <center> Связь МНК и решения системы линейных уравнений

### <center>Решение системы линейных уравнений
$$  \large \textbf A \textbf x = \textbf y  $$
$$ \large \textbf A^{-1} \textbf A \textbf x = \textbf A^{-1} \textbf y $$ 
$$  \large \textbf x = \textbf A^{-1} \textbf y  $$


#### <center> Заменим A на матрицу наблюдений X, а $x$ на $\theta$ (коэффициенты при переменных). В этом случае мы можем прогнать линейную регрессию с 3 наблюдениями и 3 переменными
$$ \large \textbf X \theta = \textbf y$$ \
$$ \large \textbf X^T \textbf X \theta = \textbf X^T \textbf y$$ \
$$ \large (\textbf X^T \textbf X)^{-1} \textbf X^T \textbf X  \theta = (\textbf X^T \textbf X)^{-1} \textbf X^T \textbf y$$ \
$$ \large \hat{\theta} = (\textbf X^T \textbf X)^{-1} \textbf X^T \textbf y$$

In [38]:
# Давайте решим систему линейных уравнений
import numpy as np
A = np.array([[2,5,3],[4,0,8],[1,3,0]])
y = np.array([-3, 0, 2])
np.linalg.solve(A, y)

array([ 5.42857143, -1.14285714, -2.71428571])

In [39]:
# Тот же результат мы получим, если применим формулу для МНК
np.linalg.inv(A.T @ A) @ A.T @ y

array([ 5.42857143, -1.14285714, -2.71428571])

**Но почему для решения линейных системных уравнений следует использовать формулу для МНК вместо простой формулы?**

Давайте добавим наблюдение к нашей простой модели

In [40]:
A = np.array([[2,5,3],[4,0,8],[1,3,0], [2,4,5]])
y = np.array([-3, 0, 2, 5])
np.linalg.solve(A, y)

LinAlgError: Last 2 dimensions of the array must be square

Мы не смогли получить оценки, потому что **обратная матрица существует только для квадратных матриц!**

Умножение на $X^T$ позволяет получить квадратные матрицы без изменения соотношения между X и y. 

Формула МНК для решения уравнения Ax=b выводится из минимизации $(Ax - b)^T(Ax-b)$.

# Прикладная статистика

In [48]:
# Случайные величины
x = np.random.random_sample((1, 100))
y = np.random.random_sample((1, 100))

##### <center>Основные выборочные характеристики в статистике:

$$ \bar{x} = \frac {\sum_i {x_i}} {n} $$

$$ \sigma^2 = \frac {\sum_i  {(x_i - \bar{x})^2}} {n} $$

$$ \sigma = \sqrt{\sigma^2} $$

$$ Cov(x,y) = \frac{1}{n}\sum_i  {[(x_i - \bar{x}) \cdot (y_i - \bar{y})]} $$ <center> - мера связи между переменными. НО! Ковариация является безразмерной величиной

$$ Corr(x,y) = \frac {Cov(x,y)} {\sigma(x) \cdot \sigma(y)} $$ <center> - мера тесноты линейной связи между двумя переменными

##### <center> Всегда помните: КОРРЕЛЯЦИЯ НЕ ОЗНАЧАЕТ ПРИЧИННО-СЛЕДСТВЕННУЮ СВЯЗЬ МЕЖДУ ПЕРЕМЕННЫМИ!!!

In [49]:
print(f"Выборочное среднее = {x.mean(), y.mean()}")
print(f"Выборочная дисперсия = {x.var(), y.var()}")
print(f"Выборочное стандартное отклонение = {x.std(), y.std()}")

Выборочное среднее = (0.49752944979532976, 0.4820174686636644)
Выборочная дисперсия = (0.07810400591714982, 0.08100872564098884)
Выборочное стандартное отклонение = (0.27947093930702316, 0.28462031839099056)


In [50]:
# Ковариационная матрица
np.cov(x, y)

array([[ 0.07889294, -0.00702589],
       [-0.00702589,  0.081827  ]])

In [51]:
# Корреляционная матрица
np.corrcoef(x, y)

array([[ 1.        , -0.08744485],
       [-0.08744485,  1.        ]])

## <center> МНК-оценки. Случай парной регрессии

$$ \textbf y_i = \alpha + \beta \textbf x_i + \epsilon_i $$
$$ \epsilon_i = \textbf y_i - \beta \textbf x_i $$
$$ \sum_{i} \epsilon_i^2 \rightarrow  \underset{\alpha, \beta}{min}$$
$$ \sum_{i} (\textbf y_i - \alpha - \beta \textbf x_i)^2 \rightarrow  \underset{\alpha, \beta}{min}$$

#### <center> ...
$$ \hat{\beta} = \frac{cov(x, y)}{var(x)}, \hat{\alpha} = \bar{y} - \hat{\beta} \bar{x} $$




## <center>МНК-оценки. Добавим вторую переменную.

<center> Пусть мы добавим в парную регрессию вторую переменную $z$. Как изменится знак для первой переменной?
    
$$\beta - \beta_x = \beta_z \frac{cov(x, z)}{var(x)}$$

Датасет "Квартиры в пригородах Бостона": https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

CRIME: Это уровень преступности на душу населения по городам \
ZM: Это доля жилой земли, зонированной для участков более 25 000 кв. Футов. \
INDUS: Это доля не торговых площадей в каждом городе. \
CHAS: Это фиктивная переменная реки Чарльз (она равна 1, если тракт ограничивает реку; 0 в противном случае) \
NOX: это концентрация оксидов азота (частей на 10 миллионов) \
РМ: это среднее количество комнат на одно жилище \
AGE: Это доля занятых владельцем единиц, построенных до 1940 года \
DIS: Это взвешенные расстояния до пяти бостонских центров занятости \
RAD: Это показатель доступности радиальных магистралей \
TAX: это полная стоимость налога на недвижимость на 10 000 долларов \
PTRATIO: Это соотношение учеников и учителей по городам \
BLACK: Это рассчитывается как 1000 (Bk - 0,63) ², где Bk - это доля людей афроамериканского происхождения по городам. \
LSTAT: это процент ниже статуса населения \
MEDV: это средняя стоимость домов, занимаемых владельцами, в 1000 долларов

In [67]:
import numpy as np
from sklearn.datasets import load_boston 
y, X = load_boston()['target'], load_boston()['data']
np.hstack([np.ones([X.shape[0], 1]), X])
# Добавим вектор единиц (модели с константой)
X = np.hstack([np.ones([X.shape[0], 1]), X])
y_name = 'price'
X_names = list(load_boston()['feature_names'])
X_names.insert(0,"const")

In [68]:
X_names

['const',
 'CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

In [69]:
# Парная регрессия с переменной CRIME
X_reg = X[:, :2]
reg_crime = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y 
reg_crime

array([24.03310617, -0.41519028])

In [72]:
np.mean(y)

22.532806324110677

In [83]:
np.corrcoef(X_reg_cent[:, 1] / np.std(X_reg_cent[:, 1]), X_reg[:, 1])

array([[1., 1.],
       [1., 1.]])

In [73]:
X_reg_cent = X_reg.copy()
X_reg_cent[:, 1] = X_reg_cent[:, 1] - np.mean(X_reg_cent[:, 1])
np.linalg.inv(X_reg_cent.T @ X_reg_cent) @ X_reg_cent.T @ y 

In [79]:
# Добавим переменную ZM
X_reg = X[:, :3]
reg_crime_zm = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y 
reg_crime_zm

array([22.48562811, -0.35207832,  0.11610909])

In [87]:
print(f"Коэффициент изменился на {reg_crime[1] - reg_crime_zm[1]}")
diff_coef = reg_crime_zm[2] * np.cov(X[:, 1], X[:, 2])[0,1] / np.var(X[:, 1])
print(f"Согласно формуле коэффициент изменился на {diff_coef}")

Коэффициент изменился на -0.06311196227482346
Согласно формуле коэффициент изменился на -0.06323693645754555


In [88]:
np.allclose(reg_crime[1] - reg_crime_zm[1], diff_coef)

False

<center> Они почти равны, но не равны. Почему? Дело в том, что в numpy существует несколько способов вычисления дисперсий, ковариаций и корреляций - смещенные и несмещенные выборочные оценки своих теоретических аналогов. По умолчанию numpy использует смещенные оценки (в формуле ковариации, корреляции и дисперсии деление происходит не на $n-1$, а на  $n$. Исправим это.

In [89]:
print(f"Коэффициент изменился на {reg_crime[1] - reg_crime_zm[1]}")
diff_coef = reg_crime_zm[2] * np.cov(X[:, 1], X[:, 2], 
                                     ddof = 1)[0,1] / np.var(X[:, 1],
                                                            ddof = 1)
print(f"Согласно формуле коэффициент изменился на {diff_coef}")
# Порядок округления
n_round = 14
assert np.round(reg_crime[1] - reg_crime_zm[1], n_round) == np.round(diff_coef, n_round)

Коэффициент изменился на -0.06311196227482346
Согласно формуле коэффициент изменился на -0.06311196227482312


Заметим, что $ \frac{cov(x, z)}{var(x)} $ есть не что иное как оценка коэффициента наклона в регрессии $z$ на $ x$. Оценим при помощи МНК регрессию $z$ на $ x$:

In [91]:
np.linalg.lstsq(a=X[:, :2], b=X[:, 2], rcond=None)[0]

array([13.32779403, -0.54355745])

In [92]:
print(f"Коэффициент изменился на {reg_crime[1] - reg_crime_zm[1]}")
diff_coef = reg_crime_zm[2] * np.linalg.lstsq(a=X[:, :2], b=X[:, 2], rcond=None)[0][1]
print(f"Согласно формуле коэффициент изменился на {diff_coef}")
# Порядок округления
n_round = 14
assert np.round(reg_crime[1] - reg_crime_zm[1], n_round) == np.round(diff_coef, n_round)

Коэффициент изменился на -0.06311196227482346
Согласно формуле коэффициент изменился на -0.06311196227482314


А что, если мы добавим в регрессию не одну, а две новые переменные? Здесь уже на помощь приходит **теорема Фриша-Во-Ловела**, которая гласит, что оценка МНК во множественной регрессии при первом факторе получена в результате очистки от влияния остальных факторов. Подробней здесь.
http://bdemeshev.github.io/em301/notes_2016/frish-and-co.html

Приведем пример.

In [93]:
# Добавим переменную ZM, INDUS
X_reg = X[:, :4]
reg_price_crime_zm_indus = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y
reg_price_crime_zm_indus

array([27.39464678, -0.24862831,  0.05850082, -0.41557782])

In [94]:
# Оценим регрессию PRICE на ZM, INDUS
X_reg = X[:, [0, 2,3]]
reg_price_zm_indus = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y
reg_price_indus_residuals = y - X_reg @ reg_price_zm_indus

In [95]:
# Оценим регрессию CRIME на ZM, INDUS
X_reg, y = X[:, [0, 2,3]], X[:, 1]
reg_crime_zm_indus = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y
reg_crime_zm_indus_residuals = y - X_reg @ reg_crime_zm_indus

In [96]:
# Оценим остатки от регрессии PRICE на ZM, INDUS на остатки от регрессии CRIME на ZM, INDUS
X_reg, y = reg_crime_zm_indus_residuals, reg_price_indus_residuals
X_reg = np.hstack([np.ones([X_reg.shape[0], 1]), np.array([X_reg]).T])
reg_PRICE_res_CRIME_res = np.linalg.inv(X_reg.T @ X_reg) @ X_reg.T @ y

In [101]:
n_dig = 14
np.round(reg_PRICE_res_CRIME_res[1], n_dig) == np.round(reg_price_crime_zm_indus[1], n_dig)

False

In [100]:
np.allclose(reg_PRICE_res_CRIME_res[1], reg_price_crime_zm_indus[1])

True

# kNN - метод ближайших соседей

Реализация метода ближайших соседей для решения проблемы классификации без готовых пакетов, используя только numpy на датасете титаник.

Задача: используя признаки Fare (стоимость билета на борт) и Pclass (класс каюты), попробуем классифицировать пассажиров в зависимости от того, выжили они или нет (Survived = 1 или 0)

In [102]:
from catboost.datasets import titanic
titanic_train, titanic_test = titanic()

# Целевая переменная на тренировочном наборе данных
y_train = titanic_train.Survived.values
titanic_train['Age'] = titanic_train['Age'].fillna(titanic_train['Age'].mean())
titanic_test['Age'] = titanic_test['Age'].fillna(titanic_train['Age'].mean())
# Объясняющий признак на тренировочной и валидационной выборке
X_train, X_test = titanic_train[["Fare", "Age", "Pclass"]].values, \
                   titanic_test[["Fare", "Age", "Pclass"]].values
# # # Удалим пропуски из тестовой выборки
X_test = X_test[np.isnan(X_test).sum(axis=1)==0]

# Стандартизируем объясняющие признаки
X_train_knn_scaled = (X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)
X_test_knn_scaled = (X_test - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

In [103]:
?np.linalg.norm

In [116]:
%%time
def get_dist(x):
    ''' Создаем матрицу с попарными расстояниями между признаками на тестовой выборке
    и тренировочной'''
    return np.linalg.norm(x - X_train_knn_scaled, axis = 1)
dist_mat = np.apply_along_axis(get_dist, 1, X_test_knn_scaled)

# Берем 7 ближайших соседей (первые 7 индексов по возрастанию в тренировочной выборке)
n = 7
dist_mat_sort_index = dist_mat.argpartition(kth = n, axis = 1)[:, 0:n]
# dist_mat_sort_index = dist_mat.argsort(axis = 1)[:, 0:n]
# Заменяем в остортированной матрице расстояний индексы на соответствующие им значения целевой переменной

dist_target = np.apply_along_axis(lambda x: y_train[x], 1, dist_mat_sort_index)

# Предсказываем целевую переменную методом большинства
y_pred = np.round(dist_target.mean(axis = 1),0)

CPU times: user 15.4 ms, sys: 3.89 ms, total: 19.3 ms
Wall time: 20.8 ms


In [121]:
X_test[0, :]

array([ 7.8292, 34.5   ,  3.    ])

In [31]:
dist_mat[0, 1:7].argpartition(kth = 5)

array([0, 1, 2, 3, 4, 5])

In [28]:
dist_mat[0, 1:7].argpartition(kth = 4)

array([4, 2, 1, 3, 0, 5])

In [29]:
dist_mat[0, 1:7].argpartition(kth = 3)

array([3, 4, 1, 2, 0, 5])

In [35]:
dist_mat[0, 1:7].argpartition(kth = 2)

array([3, 4, 1, 0, 2, 5])

In [36]:
dist_mat[0, 1:7].argpartition(kth = 1)

array([3, 4, 2, 0, 1, 5])

In [37]:
dist_mat[0, 1:7].argpartition(kth = 0)

array([3, 1, 2, 0, 4, 5])

In [32]:
np.round(dist_mat[0, 1:7], 2)

array([2.73, 0.65, 2.56, 0.04, 0.37, 2.96])

In [33]:
np.partition([3,4,2,1], 0)

array([1, 4, 2, 3])

In [146]:
dist_target[0]

array([1, 0, 0, 0, 1, 1, 0])

In [9]:
dist_mat_sort_index

array([[614,   4, 843, ..., 847, 758, 590],
       [771, 132, 203, ..., 592, 873, 276],
       [ 33, 772, 232, ..., 570,  15, 684],
       ...,
       [465, 528, 400, ..., 471, 661, 561],
       [ 95, 304, 121, ..., 837, 564,  45],
       [128, 533,  48, ..., 301, 888, 783]])

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn_7 = KNeighborsClassifier(7)
knn_7.fit(X_train_knn_scaled, y_train)
knn_sklearn_predict = knn_7.predict(X_test_knn_scaled.astype('float32'))
knn_sklearn_predict_proba = knn_7.predict_proba(X_test_knn_scaled.astype('float32'))

In [18]:
y_pred[y_pred != knn_sklearn_predict].shape

(6,)

In [19]:
knn_sklearn_predict_proba

array([[1.        , 0.        ],
       [1.        , 0.        ],
       [0.71428571, 0.28571429],
       [0.14285714, 0.85714286],
       [1.        , 0.        ],
       [0.42857143, 0.57142857],
       [1.        , 0.        ],
       [0.42857143, 0.57142857],
       [0.85714286, 0.14285714],
       [0.71428571, 0.28571429],
       [1.        , 0.        ],
       [0.42857143, 0.57142857],
       [0.28571429, 0.71428571],
       [0.85714286, 0.14285714],
       [0.42857143, 0.57142857],
       [0.28571429, 0.71428571],
       [0.57142857, 0.42857143],
       [0.71428571, 0.28571429],
       [0.14285714, 0.85714286],
       [0.71428571, 0.28571429],
       [0.57142857, 0.42857143],
       [0.28571429, 0.71428571],
       [0.42857143, 0.57142857],
       [0.14285714, 0.85714286],
       [0.42857143, 0.57142857],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.71428571, 0.28571429],
       [0.42857143, 0.57142857],
       [0.42857143, 0.57142857],
       [0.

limit_output extension: Maximum message size of 10000 exceeded with 13761 characters

In [20]:
knn_sklearn_predict_proba[y_pred != knn_sklearn_predict]

array([[0.42857143, 0.57142857],
       [0.57142857, 0.42857143],
       [0.57142857, 0.42857143],
       [0.57142857, 0.42857143],
       [0.42857143, 0.57142857],
       [0.42857143, 0.57142857]])

6 из 417 прогнозных значений нашего ручного алгоритма отличаются от предсказанного через реализацию sklearn. 

**Задание со звездочкой: подумайте, почему?**